export const ENTER_EMAIL = 'ENTER_EMAIL';
export const ENTER_PASSWORD = 'ENTER_PASSWORD';
export const REGISTER_SUBMIT = 'REGISTER_SUBMIT';
export const LOGIN_SUBMIT = 'REGISTER_SUBMIT';
export const ENTER_GOAL_TITLE = 'ENTER_GOAL_TITLE';
export const ENTER_GOAL_INFO = 'ENTER_GOAL_INFO';
export const ADD_GOAL_SUBMIT = 'ADD_GOAL_SUBMIT';
export const DELETE_GOAL = 'DELETE_GOAL';


export const TOGGLE_LOGIN = 'TOGGLE_LOGIN';